/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentPolicyRouteImport } from './routes/agent-policy'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResortAgentsRouteImport } from './routes/resort-agents'
import { Route as TalaResearchRouteImport } from './routes/tala-research'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminOperatorsRouteImport } from './routes/admin.operators'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminSocialMediaRouteImport } from './routes/admin.social-media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPolicyRoute = AgentPolicyRouteImport.update({
  id: '/agent-policy',
  path: '/agent-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortAgentsRoute = ResortAgentsRouteImport.update({
  id: '/resort-agents',
  path: '/resort-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const TalaResearchRoute = TalaResearchRouteImport.update({
  id: '/tala-research',
  path: '/tala-research',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperatorsRoute = AdminOperatorsRouteImport.update({
  id: '/admin/operators',
  path: '/admin/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocialMediaRoute = AdminSocialMediaRouteImport.update({
  id: '/admin/social-media',
  path: '/admin/social-media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-policy': typeof AgentPolicyRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/resort-agents': typeof ResortAgentsRoute
  '/tala-research': typeof TalaResearchRoute
  '/terms': typeof TermsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/social-media': typeof AdminSocialMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-policy': typeof AgentPolicyRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/resort-agents': typeof ResortAgentsRoute
  '/tala-research': typeof TalaResearchRoute
  '/terms': typeof TermsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/social-media': typeof AdminSocialMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-policy': typeof AgentPolicyRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/resort-agents': typeof ResortAgentsRoute
  '/tala-research': typeof TalaResearchRoute
  '/terms': typeof TermsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/social-media': typeof AdminSocialMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-policy'
    | '/agents'
    | '/checkout'
    | '/contact'
    | '/ecosystem'
    | '/privacy'
    | '/resort-agents'
    | '/tala-research'
    | '/terms'
    | '/admin/operators'
    | '/admin/orders'
    | '/admin/social-media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-policy'
    | '/agents'
    | '/checkout'
    | '/contact'
    | '/ecosystem'
    | '/privacy'
    | '/resort-agents'
    | '/tala-research'
    | '/terms'
    | '/admin/operators'
    | '/admin/orders'
    | '/admin/social-media'
  id:
    | '__root__'
    | '/'
    | '/agent-policy'
    | '/agents'
    | '/checkout'
    | '/contact'
    | '/ecosystem'
    | '/privacy'
    | '/resort-agents'
    | '/tala-research'
    | '/terms'
    | '/admin/operators'
    | '/admin/orders'
    | '/admin/social-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentPolicyRoute: typeof AgentPolicyRoute
  AgentsRoute: typeof AgentsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  PrivacyRoute: typeof PrivacyRoute
  ResortAgentsRoute: typeof ResortAgentsRoute
  TalaResearchRoute: typeof TalaResearchRoute
  TermsRoute: typeof TermsRoute
  AdminOperatorsRoute: typeof AdminOperatorsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSocialMediaRoute: typeof AdminSocialMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-policy': {
      id: '/agent-policy'
      path: '/agent-policy'
      fullPath: '/agent-policy'
      preLoaderRoute: typeof AgentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resort-agents': {
      id: '/resort-agents'
      path: '/resort-agents'
      fullPath: '/resort-agents'
      preLoaderRoute: typeof ResortAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tala-research': {
      id: '/tala-research'
      path: '/tala-research'
      fullPath: '/tala-research'
      preLoaderRoute: typeof TalaResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operators': {
      id: '/admin/operators'
      path: '/admin/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AdminOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/social-media': {
      id: '/admin/social-media'
      path: '/admin/social-media'
      fullPath: '/admin/social-media'
      preLoaderRoute: typeof AdminSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentPolicyRoute: AgentPolicyRoute,
  AgentsRoute: AgentsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  PrivacyRoute: PrivacyRoute,
  ResortAgentsRoute: ResortAgentsRoute,
  TalaResearchRoute: TalaResearchRoute,
  TermsRoute: TermsRoute,
  AdminOperatorsRoute: AdminOperatorsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSocialMediaRoute: AdminSocialMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
